server:
  port: 8080

spring:
  application:
    name: Bank Management System
  jackson:
    time-zone: Africa/Lagos
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_management_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC
          '[batch_size]': 25
        query:
          '[fail_on_pagination_over_collection_fetch]': true
          '[in_clause_parameter_padding]': true
        '[generate_statistics]': false
        '[order_updates]': true
        '[order_inserts]': true
        connection:
        '[provider_disables_autocommit]': true
        '[default_schema]': public
        ddl-auto: none 
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase: 
    drop-first: false
    enabled: true   
    default-schema: public
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.yml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
    level:
      ROOT: INFO
      '[org.hibernate.SQL]': INFO
      '[com.example.ecom]': DEBUG
      
cloudinary:
  cloud_name: dbvv8bryb
  api_key: 574394318681495
  api_secret: HVSBv2I6uL1eckjqbxBpMvDH_K8
      
app:
  jwt:
    secret: uE9Z2NFgDgy5ykNQy6zjUPx0FVqzffGu1eS05Lr8chc%
    access-token-expiration: 604800000
    # access-token-expiration: 1800000   # 30 minutes
    refresh-token-expiration: 604800000  # e.g., 7 days in milliseconds
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
springdoc:
  packages-to-scan: com.example.bank
  swagger-ui:
    persist-authorization: true