server:
  port: ${PORT:8080}

spring:
  application:
    name: Bank Management System
  jackson:
    time-zone: Africa/Lagos
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC
          '[batch_size]': 25
        query:
          '[fail_on_pagination_over_collection_fetch]': true
          '[in_clause_parameter_padding]': true
        '[generate_statistics]': false
        '[order_updates]': true
        '[order_inserts]': true
        connection:
        '[provider_disables_autocommit]': true
        '[default_schema]': public
        ddl-auto: none 
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase: 
    drop-first: false
    enabled: true   
    default-schema: public
    contexts: prod
    change-log: classpath:db/changelog/db.changelog-master.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    ROOT: INFO
    '[org.hibernate.SQL]': INFO
    '[com.example.ecom]': DEBUG

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${CLOUD_API_KEY}
  api_secret: ${CLOUD_API_SECRET}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 604800000
    refresh-token-expiration: 604800000
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

springdoc:
  packages-to-scan: com.example.bank
  swagger-ui:
    persist-authorization: true

banking:
  transaction:
    withdrawal:
      fee: 10.00
    approval-threshold: 100000.00
    transfer:
      fee: 25.00
    vat:
      rate: 0.075
  bank:
    control:
      account: "BANK_CONTROL_000001"
